### ISSUE TITLE
OutOfBoundsException

### ISSUE THREAD

**Issue by eFFemeer** [JeroenDeDauw/Maps#101]
Problem (again) with Maps on Mediawiki:
```
Exception encountered, of type "OutOfBoundsException"

[f05b7a5e] /wiki/Drebbels_Wandeling OutOfBoundsException from line 130 of /www/htdocs/drebbel/wiki/extensions/SemanticMediaWiki/vendor/param-processor/param-processor/src/ParamDefinitionFactory.php: Unknown parameter type "mappingservice".

Backtrace:
#0 /www/htdocs/drebbel/wiki/extensions/SemanticMediaWiki/vendor/param-processor/param-processor/src/ParamDefinitionFactory.php(213): ParamProcessor\ParamDefinitionFactory->newDefinition(string, string, string, string, boolean)
#1 /www/htdocs/drebbel/wiki/extensions/SemanticMediaWiki/vendor/param-processor/param-processor/src/ParamDefinition.php(595): ParamProcessor\ParamDefinitionFactory->newDefinitionFromArray(array)
#2 /www/htdocs/drebbel/wiki/vendor/param-processor/param-processor/src/Processor.php(223): ParamProcessor\ParamDefinition::getCleanDefinitions(array)
#3 /www/htdocs/drebbel/wiki/vendor/param-processor/param-processor/src/Processor.php(212): ParamProcessor\Processor->setParameters(array, array, boolean)
#4 /www/htdocs/drebbel/wiki/extensions/SemanticMediaWiki/extensions/Validator/src/legacy/ParserHook.php(366): ParamProcessor\Processor->setFunctionParams(array, array, array)
#5 /www/htdocs/drebbel/wiki/extensions/SemanticMediaWiki/extensions/Validator/src/legacy/ParserHook.php(294): ParserHook->validateAndRender(array, integer)
#6 [internal function]: ParserHook->renderFunction(Parser, string, string, string, string, string, string, string)
#7 /www/htdocs/drebbel/wiki/extensions/SemanticMediaWiki/extensions/Validator/src/legacy/ParserHook.php(336): call_user_func_array(array, array)
#8 /www/htdocs/drebbel/wiki/extensions/SemanticMediaWiki/extensions/Validator/src/legacy/ParserHook.php(610): ParserHook->renderFunctionObj(Parser, PPFrame_DOM, array)
#9 [internal function]: ParserHookCaller->runFunctionHookObj(Parser, PPFrame_DOM, array)
#10 /www/htdocs/drebbel/wiki/includes/parser/Parser.php(3789): call_user_func_array(array, array)
#11 /www/htdocs/drebbel/wiki/includes/parser/Parser.php(3523): Parser->callParserFunction(PPFrame_DOM, string, array)
#12 /www/htdocs/drebbel/wiki/includes/parser/Preprocessor_DOM.php(1177): Parser->braceSubstitution(array, PPFrame_DOM)
#13 /www/htdocs/drebbel/wiki/includes/parser/Parser.php(3342): PPFrame_DOM->expand(PPNode_DOM, integer)
#14 /www/htdocs/drebbel/wiki/includes/parser/Parser.php(1239): Parser->replaceVariables(string)
#15 /www/htdocs/drebbel/wiki/includes/parser/Parser.php(439): Parser->internalParse(string)
#16 /www/htdocs/drebbel/wiki/includes/content/WikitextContent.php(331): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#17 /www/htdocs/drebbel/wiki/includes/content/AbstractContent.php(497): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#18 /www/htdocs/drebbel/wiki/includes/poolcounter/PoolWorkArticleView.php(140): AbstractContent->getParserOutput(Title, integer, ParserOptions)
#19 /www/htdocs/drebbel/wiki/includes/poolcounter/PoolCounterWork.php(123): PoolWorkArticleView->doWork()
#20 /www/htdocs/drebbel/wiki/includes/page/Article.php(676): PoolCounterWork->execute()
#21 /www/htdocs/drebbel/wiki/includes/actions/ViewAction.php(44): Article->view()
#22 /www/htdocs/drebbel/wiki/includes/MediaWiki.php(490): ViewAction->show()
#23 /www/htdocs/drebbel/wiki/includes/MediaWiki.php(287): MediaWiki->performAction(Article, Title)
#24 /www/htdocs/drebbel/wiki/includes/MediaWiki.php(714): MediaWiki->performRequest()
#25 /www/htdocs/drebbel/wiki/includes/MediaWiki.php(508): MediaWiki->main()
#26 /www/htdocs/drebbel/wiki/index.php(41): MediaWiki->run()
#27 {main}
```
**My version table:**

*Installed software*
Product	Version
MediaWiki	1.26.2
PHP	5.3.29 (apache2handler)
MySQL	5.0.95
Entry point URLs
Entry point	URL
Article path	/wiki/$1
Script path	/wiki
index.php	/wiki/index.php
api.php	/wiki/api.php
load.php	/wiki/load.php
Installed skins
Skin	Version
Cologne Blue	–
Modern	–
MonoBook	–
Vector	–
Installed extensions
Semantic extensions
Extension	Version
Semantic Maps	3.2
Semantic MediaWiki	2.3.1
Special pages
Extension	Version
BlockandNuke	–
CategoryTree	–
Collection	1.7.0
ContactPage	2.2
MaintenanceShell	0.5.0
Renameuser	–
Replace Text	1.1.1
Semantic Forms	3.4
Parser hooks
Extension	Version
BrowserHistoryLink	1.1
CategoryGallery	1.0.1
CategoryTree	–
Cite	–
DynamicPageList (third party)	2.3.0
EImage	2.0.0
EmailForm	0.8.1
Embed Document	0.13
GoogleDocs4MW	1.1
InteractiveTimeline	0.1.0
Javascript Slideshow	1.2.3
Maps	3.4
NamespaceHTML	0.2
NoTitle	0.2.0
PDF Include	1.3
TimelineTable	2.0
VideoPlayer	1
Widgets	1.2
YouTube	1.9.0
Spam prevention
Extension	Version
Anti-spam by CleanTalk	1.4.1
ConfirmEdit	1.4.0
DataValues
Extension	Version
DataValues	1.0
DataValues Common	0.2.3
DataValues Geo	1.1.5
DataValues Interfaces	0.1.5
DataValues Validators	0.1.2
Other
Extension	Version
BetaFeatures	0.1
CollapsibleVector	0.1.10
Gadgets	–
GeoData	–
MultimediaViewer	0.3.0
ParserHooks	1.4.0
PCR GUI Inserts	1.0
PHPExcel	1.8.0
ReCaptcha	–
Validator	2.0.4

*Installed libraries*
Library	Version
composer/installers	1.0.22
composer/semver	1.0.0
cssjanus/cssjanus	1.1.1
data-values/common	0.2.3
data-values/data-values	1.0.0
data-values/geo	1.1.5
data-values/interfaces	0.1.5
data-values/validators	0.1.2
liuggio/statsd-php-client	1.0.16
mediawiki/at-ease	1.1.0
mediawiki/parser-hooks	1.4
onoi/blob-store	1.1.0
onoi/cache	1.2.0
onoi/callback-container	1.0.0
onoi/event-dispatcher	1.0.0
onoi/http-request	1.3.0
onoi/message-reporter	1.0.0
oojs/oojs-ui	0.12.12
oyejorge/less.php	1.7.0.9
param-processor/param-processor	1.2.2
psr/log	1.0.0
serialization/serialization	3.2.1
wikimedia/assert	0.2.2
wikimedia/cdb	1.3.0
wikimedia/composer-merge-plugin	1.3.0
wikimedia/ip-set	1.0.1
wikimedia/utfnormal	1.0.3
wikimedia/wrappedstring	2.0.0
zordius/lightncandy	0.21

*Parser function hooks*
anchorencode, arraymap, arraymaptemplate, ask, autoedit, basepagename, basepagenamee, bidi, canonicalurl, canonicalurle, cascadingsources, categorytree, concept, coordinates, declare, default_form, defaultsort, display_line, display_map, display_point, display_points, displaytitle, distance, dpl, dplchapter, dplmatrix, dplnum, dplreplace, dplvar, eimage, eimagea, filepath, finddestination, formatdate, formatnum, forminput, formlink, formredlink, fullpagename, fullpagenamee, fullurl, fullurle, gender, geocode, geodistance, grammar, info, int, language, lc, lcfirst, localurl, localurle, mapsdoc, namespace, namespacee, namespacenumber, ns, nse, numberingroup, numberofactiveusers, numberofadmins, numberofarticles, numberofedits, numberoffiles, numberofpages, numberofusers, padleft, padright, pageid, pagename, pagenamee, pagesincategory, pagesize, plural, protectionlevel, queryformlink, revisionday, revisionday2, revisionid, revisionmonth, revisionmonth1, revisiontimestamp, revisionuser, revisionyear, rootpagename, rootpagenamee, set, set_recurring_event, show, slideshow, smwdoc, special, speciale, subjectpagename, subjectpagenamee, subjectspace, subjectspacee, subobject, subpagename, subpagenamee, tag, talkpagename, talkpagenamee, talkspace, talkspacee, uc, ucfirst, urlencode and widget

**Comment by eFFemeer** [comment]
Is this something I can repair myself?

**Comment by JeroenDeDauw** [comment]
This looks like something went wrong with how you set up your wiki and extensions. I can't deduce what from this error though. Not very up to speed with the MW stuff at present, so perhaps someone like @kghbln might have an idea of what went wrong.

Or perhaps you can describe how you installed the extensions.

**Comment by eFFemeer** [comment]
I must say that Composer causing me lots of problems these days. It's is not clear at all why some extensions can be installed and others not. Attached please find my composer.json. I'll try to play around with it.
[composer.json.txt](https://github.com/JeroenDeDauw/Maps/files/90063/composer.json.txt)

**Comment by kghbln** [comment]
From your composer.json file
```
...
	"require": {
		"mediawiki/maps": "*",
		"composer/semver": "1.0.0",
		"cssjanus/cssjanus": "1.1.1",
		"ext-iconv": "*",
		"liuggio/statsd-php-client": "1.0.16",
		"oyejorge/less.php": "1.7.0.9",
		"mediawiki/at-ease": "1.1.0",
		"oojs/oojs-ui": "0.12.12",
		"php": ">=5.3.3",
		"psr/log": "1.0.0",
		"wikimedia/assert": "0.2.2",
		"wikimedia/cdb": "1.3.0",
		"wikimedia/composer-merge-plugin": "1.3.0",
		"wikimedia/ip-set": "1.0.1",
		"wikimedia/utfnormal": "1.0.3",
		"wikimedia/wrappedstring": "2.0.0",
		"mediawiki/semantic-maps": "*",
		"mediawiki/semantic-media-wiki": "2.3.1",
		"mediawiki/parser-hooks": "~1.4",
		"zordius/lightncandy": "0.21"
	},
...
```
you should remove the lines containing
``"mediawiki/maps": "*",`` and ``"mediawiki/parser-hooks": "~1.4",``
since both extensions will be loaded as a dependency via the other extensions.

Since the composer-merge-plugin is available you could create a "composer.local.json":

```
{
        "require": {
                "mediawiki/semantic-media-wiki": "~2",
                "mediawiki/semantic-maps": "~3"
        }
}
```
and leave the "composer.json" of MediaWiki untouched as it was.

**Comment by eFFemeer** [comment]
Thank you kghbin. I will do that!

**Comment by kghbln** [comment]
Keeping fingers crossed. Using Windows is probably complicating things. Well dunno since I have no experience with Windows in this respect.

**Comment by eFFemeer** [comment]
Windows Composer seems to work (more or less) but required a lot of trial
and error. Quiet untransparent application because of strange components
such as oyejorge, zordius etc. I'm curious what will happen when new
extensions will be adapted to Composer.

On Thu, Jan 14, 2016 at 7:37 PM, Karsten Hoffmeyer <notifications@github.com

**Comment by JeroenDeDauw** [comment]
Thanks a lot for explaining @kghbln!

**Comment by fellam** [comment]
Finally I was able to pick up this from my TODO list and sort it out.
Hope this can be usefull to someone else: in my case, none of the above solution worked out.

**NOTEs:** The solutions mentioned here are workaround, needed for possible error during the various installation and customization. You should know the meaning of what you are doing if you choose to follow the same approach.

**ISSUE:** The "mappingservice" is defined by the Map extension as well as others definitions such as coordinate, mapslocation, mapsline and so on..
Those definitions are added to the GLOBALS['wgParamDefinitions'] array when the Maps extension is included (and on my debug this was working).

The OutOfBoundsException might be a bit misleading as this is not an OutOfBoundsException but a missing key in GLOBALS['wgParamDefinitions'] array.

The **ROOT CAUSE** was that the GLOBALS['wgParamDefinitions'] was somehow re-generated on the way and lost those definition.

After some debugging, the problem were several:

1) SemanticMediaWiki installed trough composer somehow installed and it's own param-processor library, and when loaded, it was re-initializing the GLOBALS['wgParamDefinitions'] (eventually loosing the configuration of Maps extension).

_Suggestion:_ be sure no "vendor" folder are in your ../wiki/extensions/SemanticMediaWiki folder.
You should always run composer from your wiki root path, and there should only be one "vendor" folder on wiki root path containing all the needed libraries.

_Solution:_ Simply renamed (just as backup) the vendor folder to vendor_bk after checking that all its subfolders were also installed on the ../wiki/vendor path.

2) SemanticBundle installed from git points to its own **ParamProcessor**.
This issue was alike the previous one, it seems that Semantic bundle points to its own param-processor, expected to be in the extension installation path. 
It doesn't really needs the rest of the library, but looks for a ParamProcessor custom folder, which I was not able to find in the standard param-processor library.. 

File: SemanticBundleSettings.php
<pre>
include_once( "$IP/extensions/SemanticBundle/param-processor/param- processor/src/**ParamProcessor/Processor.php**" );
include_once( "$IP/extensions/SemanticBundle/param-processor/param-processor/**DefaultConfig.php**");
</pre>

_Solution:_ As above, in order to keep consistency, I've chosen that ../wiki/vendor/ path should have been the main path for all the library installations. 
To achieve this I renamed the SemanticBundle/param-processor folder to SemanticBundle/param-processor_Custom.
Then in my pointing extensions/SemanticBundle I created a symlink pointing to ../wiki/vendor (command ln -s ../wiki/vendor/param-processor ../wiki/extensions/SemanticBundle/param-processor where the dot-dot are your full path)
At this point I had to still make the "custom" ParamProcessor folder visible, I could had simply moved it to ../wiki/vendor/param-processor, but I want to stay safe from composer, then I simply wend into the folder ../wiki/vendor/param-processor/param- processor/src/ and I created another symlink pointing to the missing directory (cmd: command ln -s ../wiki/extensions/SemanticBundle/param-processor/param- processor/src/ParamProcessor ../wiki/vendor/param-processor/param- processor/src/ParamProcessor where the dot-dot are your full path).

That is all.. I hope this was clear enough.. contact me if I you need!
<mik>
