### ISSUE TITLE
googlemaps service / stick to instance language

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#106]
Currently, probably there was some Google API change recently, the map is rendered in the language the user specified in her or his preferences and not the language of the wiki instance, i.e. if the user selected Russian the description will be rendered in Russian for every user until the cache of the page is edited or purged. This was reported [on the Maps talk page](https://www.mediawiki.org/wiki/Topic:Sy0xadix5wgyiagy) and I successfully replicated this behaviour on sandbox.smw.o

It will be nice if the rendering sticks to the language of the wiki instance or to additionally have a parameter allowing to specify the language to be used on a per map basis.

**Comment by mwjames** [comment]
>  i.e. if the user selected Russian the description will be rendered in Russian for every user until the cache of the page is edited or

Given [0] with the reference to `self::getApiScript( $GLOBALS['wgLang']->getCode() ),` where `wgLang` contains the user language [1].

What happens when you try changing it to use `wgContLang`?

[0] https://github.com/JeroenDeDauw/Maps/blob/6842093fc2d3cd26a41c0ba6ecb62a00f2101696/includes/services/GoogleMaps3/Maps_GoogleMaps3.php#L276-L292

[1] https://www.mediawiki.org/wiki/Manual:$wgLang

**Comment by kghbln** [comment]
> What happens when you try changing it to use wgContLang?

I believe you spotted it. :) Just changed the code on sandbox.smw.o and did the same thing. Now the maps is rendered only in English. Cool.

**Comment by JeroenDeDauw** [comment]
Fixed by #107?

**Comment by kghbln** [comment]
Yes, according to field tests. :) Thanks for merging.
