### ISSUE TITLE
Disable or remove Layer: functionality

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#168]
Regarding the functionality tied to the Layer: namespace introduced in Maps 3.0 https://github.com/JeroenDeDauw/Maps/blob/master/RELEASE-NOTES.md#new-features

This code was added in a dubious state and has received no maintenance since. I am not aware of anyone using this functionality, or documentation of it. I would thus not be surprised if it is currently broken.

Some serious issues with the functionality have been brought to my attention. These issues require follow up. If no one presents a good argument for keeping this functionality, I'm inclined to remove it.

If anyone is aware of users or documentation of this functionality, or is otherwise awesome of its status, please point this out.

**Comment by JeroenDeDauw** [comment]
FYI @DanweDE

**Comment by DanweDE** [comment]
The feature's code has not really been in a perfect state when initially committed by me (though it has actually been working). It was initially built on top of a much older version on maps and all I've essentially done was to rebase it to Maps 3.0 If I remember correctly. There was some very basic documentation [on one of my user pages](https://www.mediawiki.org/wiki/User:Danwe/maps_with_image_layer) how to get this running.

I have no intentions of maintaining this future since I haven't really used it ever since. So no objections from my side about just getting rid of it.

**Comment by kghbln** [comment]
Just by looking at the docu it looks like an interesting feature. However a maintainer would be needed for this so it will be better to put it to rest.

**Comment by JeroenDeDauw** [comment]
Thanks for your input. Will remove for the next release.

**Comment by kghbln** [comment]
I think it will be nice to document this in the RELEASE NOTES.
