### ISSUE TITLE
Is there documentation on how to add a new service provider?

### ISSUE THREAD

**Issue by FreedomFighterSparrow** [JeroenDeDauw/Maps#276]
I'm interested in adding support for using an obscure Israeli mapping service (govmap.gov.il).
I see currently only three services in the extension: GoogleMaps3, Leaflet and OpenLayers. While it's obvious that on the PHP side I need to extend MapsMappingService, on the Javascript side there doesn't seem to be a standard interface. Any tips for me?

Thanks,
Dror.

**Comment by JeroenDeDauw** [comment]
First off, be sure to use the development (4.x alpha) version of Maps, as I've changed some things since the last stable release with regards to mapping service registration. (Mainly throwing out not needed crud, so it should be simpler now.)

The JS gets some JSON with the data and config you need. After that point you can basically just do whatever you see fit. There is no real standard way of doing things, and no reusable code or tools you ought to be using. The existing mapping services have a similar approach (except perhaps Leaflet, I'm not up to speed with that one), though I recommend you ignore what they do and try to create the best code (simplest, easiest to read, etc) yourself. The GoogleMaps and OpenLayers code was certainly not written in a nice way.

**Comment by FreedomFighterSparrow** [comment]
OK, thanks for the information :-)
