### ISSUE TITLE
Support custom OpenLayers maps

### ISSUE THREAD

**Issue by DFelten** [JeroenDeDauw/Maps#311]
### Setup

- MW version: 1.26.3
- DB (MySQL etc.): MySQL
- PHP version: PHP 5.5.9-1ubuntu4.21

### Suggesstion
Is it possible to add custom maps? I would like to add our map of a game into our MediaWiki. The map is made with OpenLayers: https://www.elderscrollsportal.de/tes/morrowind/karte#zoom=0&lat=0&lon=0&layers=BTTFFFFFF

**Comment by JeroenDeDauw** [comment]
It is possible to add new layers via configuration: https://github.com/JeroenDeDauw/Maps/blob/master/Maps_Settings.php#L287-L329

More advanced things, such as defining attributes for your own layers, is not currently possible without modifying the code. Version 2.x of Maps "had" functionality that did this, except that the implementation was half-assed and never really worked (which is why it was removed in 3.0).

**Comment by DFelten** [comment]
Ok, thanks. Then I'm not sure if it's possible to use with our custom map or at least we have to modify the code.

**Comment by JeroenDeDauw** [comment]
Not sure if I should regard this as a question and close it or a feature request and modify the issues title.

**Comment by DFelten** [comment]
This is definitely a feature request :) I would like to use the extension with our own map.

**Comment by PeterTheOne** [comment]
@DFelten Have you tried using your own layer like Jeroen described? If yes, what is still missing to make it work. If no, please try. ;)

**Comment by JeroenDeDauw** [comment]
Going to close this due to inactivity and blocked on 0000FF
