### ISSUE TITLE
Semantic map query - "further results" link omits distance parameter

### ISSUE THREAD

**Issue by AL286** [JeroenDeDauw/Maps#314]
If I do a distance-based query, using #ask or Special:RunQuery, with the limit set to less than the number of results, then the "further results" link omits the distance part of the query.  So no further results are displayed.
Example:
https://sandbox.semantic-mediawiki.org/wiki/Utilisateur:L_Andy

**Comment by mwjames** [comment]
> then the "further results" link omits the distance part of the query. So no further results are displayed.
> https://sandbox.semantic-mediawiki.org/wiki/Utilisateur:L_Andy

Here is what happens when building a "further results" link:

* `QueryLinker` builds the string from a `Query` object
* `Query::getQueryString` is called with `true` as it requires:

```
public function getQueryString( $fresh = false ) {

	// Mostly relevant on requesting a further results link to
	// ensure that localized values are transformed into a canonical
	// representation
	if ( $fresh && $this->description !== null ) {
		return $this->description->getQueryString();
	}
```

The problem is that `SMAreaValueDescription::getQueryString` never takes into account the radius in  `return $asValue ? $queryString : "[[$queryString]]";` as part of the `$queryString` and you'd have change the method do something like the following to build a complete query string.

```
	public function getQueryString( $asValue = false ) {

		if ( $this->getDataItem() !== null ) {

			$queryString = DataValueFactory::newDataItemValue( $this->getDataItem(), $this->getPropertyCompat() )->getWikiValue();

			if ( $this->radius !== '' ) {
				// This isn't very appealing but the radius has been transformed
				// into a m representation without knowing the unit requested by
				// a user
				$unit = ( $this->radius > 1000 ? 'km' : 'm' );

				$radius = MapsDistanceParser::formatDistance(
					$this->radius,
					$unit
				);

				$queryString .= " ($radius)";
			}

			return $asValue ? $queryString : "[[$queryString]]";
		} else {
			return $asValue ? '+' : '';
		}
	}
```

PS: I don't like `$unit = ( $this->radius > 1000 ? 'km' : 'm' );` and I'd rather rely on the original value but it gets converted in the constructor.

**Comment by JeroenDeDauw** [comment]
Thanks for reporting @AL286 and thanks for figuring out a solution @mwjames.

**Comment by JeroenDeDauw** [comment]
Hah, this was kinda stupid... I suppose that method was just copied from the CoordinateDescription one and never updated. And no one complained about it for 5 years :)

**Comment by JeroenDeDauw** [comment]
@AL286 as you can see the issue is fixed now on the sandbox, so just upgrade your wiki to Maps 4.1 and all should be fluff

**Comment by AL286** [comment]
Thanks Jeroen
