### ISSUE TITLE
leaflet overlaylayers not working

### ISSUE THREAD

**Issue by krabina** [JeroenDeDauw/Maps#385]
### Setup

- Maps version:  5.0.2
- MW version: 1.27.3

### Issue

the option egMapsLeafletAvailableOverlayLayers seems to suggest that in leaflet, there can be multiple layers displayed:
https://github.com/JeroenDeDauw/Maps/blob/3f4c769762cf2e850290694d057ef7d7e2ca7454/Maps_Settings.php#L388

This seems to suggest an option |overlaylayers=
https://github.com/JeroenDeDauw/Maps/blob/8bfc98573ac68b2524ebe175b5e1d3d1c9c4af06/includes/services/Leaflet/Maps_Leaflet.php#L48-L53
It seems to do someting, but in my example (the second on the page) it is not a switchable overlay, but instead only the card set with  |overlaylayers= is displayed
http://standards.kdz.eu/index.php?title=MapsTest

Furthermore this is confusing, because with format=openlayers the syntax is:

|service=openlayers
|layers=osm-mapnik, osm-cyclemap

where with leaflet it is:
|service=leaflet
|layer=Esri.WorldStreetMap
|overlaylayers=OpenWeatherMap.Clouds

the options should be streamlined (and working)

**Comment by PeterTheOne** [comment]
Have you tried `OpenSeaMap` for example? Also check out http://leaflet-extras.github.io/leaflet-providers/preview/ to compare what the overlays should show.

**Comment by PeterTheOne** [comment]
To explain a bit more, for leaflet.. there can only be one active `layer` but multiple `overlaylayers`. Having multiple layers doesn't make sense because they would just cover each other up 100%. For some overlaylayers it makes sense to combine them, because they don't cover each other.

Why are there available layers and available overlaylayers? With these options the Admin of the Site can control which layers should be allowed, it could also be relevant security wise because data is loaded from external sources.

**Comment by krabina** [comment]
ah. I see. This makes sense. So the feature of swichtching between different base layers is available only in openlayers, not in leaflet? 
So having one active and another swichtable leaflet layer like in openlayers would be a feature request then?

**Comment by PeterTheOne** [comment]
correct.

**Comment by PeterTheOne** [comment]
This would help with switching layers: [Layer Groups and Layers Control](http://leafletjs.com/examples/layers-control/)

**Comment by PeterTheOne** [comment]
The layers issue is solved in #394, the other issue seems with OpenWeatherMap.Clouds itself.
