### ISSUE TITLE
Maps + Headertabs/collapsible elements = boom

### ISSUE THREAD

**Issue by m-art-in** [JeroenDeDauw/Maps#416]
### Setup

- Maps version: 5.2.
- MW version: 1.30
- PHP version: 7.0.7
- SMW version (if applicable): 2.5.6
- HeaderTabs: 1.2.

### Issue

Whenever a map is generated via ask-query and the result is within a headertabs structure, the map could not be loaded. Without the tag  `<headertabs />` everything is fine.

Steps to reproduce the observation: See example (and ignore the small tabs, which is an error by TweekiSkin): https://sandbox.semantic-mediawiki.org/wiki/Utilisateur:Zym/HeadertabsBug

I don't know if this is a map issue or a headertab issue. What do you think @JeroenDeDauw @yaronkoren

**Comment by JeroenDeDauw** [comment]
The Headertabs related problems don't end :) Have been getting reports like this since 2009. I'm not up to speed with what either of these extensions, or `mw-collapsible`, are doing, so can't really help here.

**Comment by kghbln** [comment]
It only works in the first tab at least this is how it used to be in the past.

**Comment by m-art-in** [comment]
> It only works in the first tab at least this is how it used to be in the past.

Thats right: Map on the first tab is looking good:
https://sandbox.semantic-mediawiki.org/wiki/Utilisateur:Zym/HeadertabsBug-AnotherTry

**Comment by JeroenDeDauw** [comment]
@m-art-in the example on the sandbox is working now, so is this issue fixed?

**Comment by m-art-in** [comment]
@JeroenDeDauw I modiefied the example and inserted a map und the 2nd tab. Then it's still not working. (btw. Headertabs looks also a bit strange in the Sandbox):

![grafik](https://user-images.githubusercontent.com/15324884/57059085-e2b57780-6cb3-11e9-983e-5edf0ddc1521.png)

Only maps on the 1st tab are fine and lokking good.

**Comment by JeroenDeDauw** [comment]
It looks like the Maps code is working fine there but that Leaflet is getting confused. This might not be fixable from the Maps side at all. You could try asking about this on the Leaflet support channels.

**Comment by kghbln** [comment]
> You could try asking about this on the Leaflet support channels.

I think Header Tabs may play a role here too. Adding something useful which requires some sort of scripting never worked with it, i.e. plain text only for tab 2 to infinite. Actually I remember asking Yaron about this in Barcelona back in 2015 and the advice was basically not to add anything but plain text to these tabs. Moreover I got the impression that there is no intention to do something about it.

> btw. Headertabs looks also a bit strange in the Sandbox

Indeed, Header Tabs is apparently broken for MW 1.32 and later. I have reported the issue [here](https://www.mediawiki.org/wiki/Topic:Uyy3qkl4907likyo).

I am closing this issue since it has most probably nothing to do at all with Maps.
