### ISSUE TITLE
Removing dependency of Composer

### ISSUE THREAD

**Issue by Tigerfell** [JeroenDeDauw/Maps#486]
### Setup

- Maps version: none (tried to install 6.0.x)
- MW version: 1.31.1 (921e265)
- PHP version: 7.2.10-0ubuntu0.18.04.1 (apache2handler)
- SMW version (if applicable): _none_
- Configuration management with [Chef](https://en.wikipedia.org/wiki/Chef_(software))

### Issue
In https://github.com/openstreetmap/operations/issues/249, we tried to install the extension to the [wiki of Openstreetmap](https://wiki.osm.org). Unfortunately, this failed as Composer and Chef interfered. As far as I understand, Composer is supposed to help with the extension management, so it is not a core part of an extension (?). 

Is there a way to remove the requirement to use Composer when using the extension?

**Comment by JeroenDeDauw** [comment]
Maps technically does not depend on Composer. It does however need some libraries and its own classes to be in the PHP autoloader. Composer can set that up. If you do not want to run composer on your server, you can run it locally and upload the resulting files. However while that works it is more complicated so not recommended unless you know what you are doing.

Recommend is the standard MediaWiki approach of installing extensions via Composer. https://www.mediawiki.org/wiki/Composer/For_extensions#Specify_the_extensions_to_be_installed

I do not understand the comments on the linked issue. The OSM wiki appears to be running recent MediaWiki with a bunch of libraries loaded. And with Wikibase installed. It seems very likely that was done by using Composer.

People are free to provide some form of tarball distribution of this extension and many others that use third party libraries. I myself won't spend time on either creating that or supporting the many problems users likely run into when attempting to use that.

Feel free to post concrete installation question here on on the mailing list. The way Maps is installed won't be changed because on one wiki people can't manage to run Composer though.

**Comment by JeroenDeDauw** [comment]
BTW Kartographer also uses a third party library so you run into the same situation there

**Comment by Tigerfell** [comment]
Ok, thanks for the information.
