### ISSUE TITLE
Tailing seperator breaks lines parameter

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#489]
> #Display_map now requires the last (;) to be removed or otherwise nothing will show. The old version didn't require that. This complicates efforts to import the lines (via the command above or some other ways including external data) because these commands will result in an extra (;) that cannot to easily eliminated but which display_map requires.

-- @acnetj in https://github.com/JeroenDeDauw/Maps/issues/488

**Comment by JeroenDeDauw** [comment]
Likely also happens with other list parameters

**Comment by JeroenDeDauw** [comment]
I had a quick look at the code in maps and suspect this is a ParamProcessor issue

**Comment by JeroenDeDauw** [comment]
At least with version 5.6 this issue appears to not be happening: https://sandbox.semantic-mediawiki.org/wiki/Maps_issue_489

@acnetj what version are you seeing this issue on?

**Comment by acnetj** [comment]
I have 5.6 now and somehow it got resolved. It was an issue with 5.0 but I couldn't upgrade it until I first upgrade to PHP 7. Just too many things to upgrade at once so I had to break down to manageable steps.

Basically I can restore the map that I had with 2.0 with some code changes (like adding "point=" not to confuse with url parameters. The biggest change would be not having semantic query with points. 

https://www.transit.wiki/Map:14-Mission

However the bug exist when you use "locations" with a semantic ask query (the same query that you cannot use "lines" to add lines to the same map that you could under version 2.X). So I cannot use "locations" to add points from external data onto a semantic map because external data produces a trailing ";". I can only use it for now on a plain map, and may add semantic query by making an ask query to produce a format usable under display_map.

See this for example with the same map (points produced by an ask query and adding additional points manually). One with a trailer ; and another without.

https://www.transit.wiki/Sandbox_3

**Comment by JeroenDeDauw** [comment]
Ok, I have created a new issue for the tailing separator breaking lines= in ask. https://github.com/JeroenDeDauw/Maps/issues/512

If there is another bug, please create a dedicated issue for it as well.
