### ISSUE TITLE
Dedicated map display functions

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#537]
This ticket exists to gauge interest for a possible addition/enhancement to Maps.

Current way to display a map:

```
{{#display_map:service=google | width=75% | type=satellite }}
```

```
{{#display_map:service=leaflet | height=200px | geojson=MyGeoJson }}
```

Proposed way:

```
{{#google_maps:width=75% | type=satellite }}
```

```
{{#leaflet:width=200px | geojson=MyGeoJson }}
```

The `display_map` syntax would still work.

### Rationale

display_map and other MediaWiki parser functions are _functions_. Just like functions in PHP and other languages, they have a set of parameters that form their signature. display_map goes against a practices for function design. Many of its parameters only make sense in certain contexts (`type=satellite` is ignored when the service is not Google Maps). By having dedicated functions for each mapping service, there are fixes lists of available parameters and there never is a need to also specify the mapping service as a parameter.

**Comment by kghbln** [comment]
Makes sense to me. What about `{{#display_googlemaps: }}` and  `{{#display_leaflet: }}` or even better `{{#googlemaps_map: }}` and  `{{#leaflet_map: }}` for consistency reasons?

**Comment by acnetj** [comment]
Another consistency to consider is the use of semantic mediawiki and the #ask or #compound_query parser functions. They use format=googlemaps or format=leaflet to indicate map type. Some of the parameters in display_map can be directly used on #ask or #compound_query.

Since display_map would still work, it doesn't appear to be much of an issue. May be just make syntax simpler for those just want a map shown. On the other hand, using this method would require individual page or template code change if there's a need to change map provider, rather than through the default via localsettings.php.

**Comment by JeroenDeDauw** [comment]
> using this method would require individual page or template code change if there's a need to change map provider, rather than through the default via localsettings.php.

Yeah... that is a pretty big drawback. There'd be no way of changing the default default either...
