### ISSUE TITLE
Category:Pages with a map rendered by the Maps extension - show or hide?

### ISSUE THREAD

**Issue by Contrafibularity** [JeroenDeDauw/Maps#58]
Pages on which the Maps extension is used are automatically included in the category "Pages with a map rendered by the Maps extension". Is this intended behaviour or do we want to hide the category from the page? I'm not really sure myself, but it does make you wonder. What's the thinking here?

**Comment by robksawyer** [comment]
:+1: 

A user should have the ability to hide "Pages with a map rendered by the Maps extension". Or, make the text shorter. Maybe just make a category called Page Maps or just Maps.

**Comment by kghbln** [comment]
Yes it is intended behaviour and no, it is not added as a hidden category so the HIDDENCAT behaviour switch has to be added manually. However since the [3.3 release](https://github.com/JeroenDeDauw/Maps/blob/master/docs/RELEASE-NOTES.md#maps-33) it is possible to set `$egMapsEnableCategory = false;` to stop Maps from adding the category. I guess this solves the issue. Pls reopen if I am wrong.

Related commits:
* https://github.com/JeroenDeDauw/Maps/commit/c0def48ac9e078831fed85984da4d03aae96808d
* https://github.com/JeroenDeDauw/Maps/commit/050ffd5096dd297b0b324ce580b2caa16612b41b

**Comment by kghbln** [comment]
@robksawyer In case you would like to make the name of the category shorter just change the system message "MediaWiki:maps-tracking-category" to what fits your needs.

**Comment by robksawyer** [comment]
Great, thanks!
