### ISSUE TITLE
Add support for Swiss coordinate system

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#600]
### Setup

- Maps version: 7.15.5 (644f021) 18:02, 6 January 2020
- MW version: MediaWiki | 1.34.0 (ae6e0c0)15:53, 27 December 2019
- PHP version: 7.2.24-0ubuntu0.18.04.1 (apache2handler)

### Issue
Add support for the E / N notation not sure what it is called properly.

### Examples
This would allow to add something like:

`{{#display_map: 2705693.512 E, 1239454.879 N }}`

or

`{{#display_map: E 2705693.512, N 1239454.879 }}`

**Comment by JeroenDeDauw** [comment]
The formats listed here https://www.semantic-mediawiki.org/wiki/Maps/Coordinate_formats are supported everywhere where Maps accepts locations, as mentioned in the first paragraph.

First N/S then E/W. You flipped them around in this example. I'm not sure what format these numbers are in since they are way too big. They cannot go above 180 or 360. So even if you put N/S and E/W in the correct order, these coordinates will not be understood.

**Comment by kghbln** [comment]
I dug a bit and found that E / N notation is a [Swiss specific notation](https://en.wikipedia.org/wiki/Swiss_coordinate_system) in connection with the 1903 and 1995 land surveys. 

I guess this is a bit too specific to implement if possible at all.

**Comment by JeroenDeDauw** [comment]
My understanding is that this is very specific and might serve half a user if implemented. That is not worth the maintenance cost.

**Comment by kghbln** [comment]
At least for the 1903 land survey there is now a dedicated extension available: https://www.mediawiki.org/wiki/Extension:CoordinateConversion
